Add picard tool?
bwlang/tools-iuc pull request #2
Opened 2019-04-08 14:17 UTC by aerijman

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

2019-04-08 15:23 UTC, bwlang requested changes
looks good - just needs some tests

2019-04-24 00:53 UTC, bwlang approved these changes
Just a couple of comments...  once those are resolved, I think this looks ready for upstream.
You should probably rebase on their master before submitting the PR.

2019-04-24 00:53 UTC, bwlang commented on tools/picard/picard_macros.xml
> +    _JAVA_OPTIONS=\${_JAVA_OPTIONS:-'-Xmx4084m -Xms256m'} &&
does this really need 4 G to run?
that's ok for our cluster but might be a problem for others.

2019-04-24 00:53 UTC, bwlang commented on tools/picard/picard_CollectSequencingArtifactsMetrics.xml
> +    <!--<param name='reference_fasta_filename' type='data' label='Reference genome' help='last reference genome used is default'/>-->
delete?

2019-04-24 01:15 UTC, aerijman commented
Thank you!

I added it as a priority to my tomorrow’s morning calendar.

Ariel

From: Brad Langhorst <notifications@github.com>
Reply-To: bwlang/tools-iuc <reply@reply.github.com>
Date: Tuesday, April 23, 2019 at 8:53 PM
To: bwlang/tools-iuc <tools-iuc@noreply.github.com>
Cc: "Erijman, Ariel" <aerijman@fredhutch.org>, Author <author@noreply.github.com>
Subject: Re: [bwlang/tools-iuc] Add picard tool? (#2)


@bwlang approved this pull request.

Just a couple of comments... once those are resolved, I think this looks ready for upstream.
You should probably rebase on their master before submitting the PR.

________________________________

In tools/picard/picard_macros.xml<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bwlang_tools-2Diuc_pull_2-23discussion-5Fr277131613&d=DwMCaQ&c=eRAMFD45gAfqt84VtBcfhQ&r=RDgR3MCuEAT5jbgfDKOU_QqPgpM8gSLjQ5SiCbZVpHQ&m=KplESfIgmb5b03YeCe7a3OHi_kd5qIdSMobMQFZ1HFE&s=QTztGEgnX2f3WOL8TeNP1K1NR9sV5-yfObVfT6B50uI&e=>:

> @@ -36,7 +36,7 @@

     ]]></token>



     <token name="@java_options@"><![CDATA[

-    _JAVA_OPTIONS=\${_JAVA_OPTIONS:-'-Xmx2048m -Xms256m'} &&

+    _JAVA_OPTIONS=\${_JAVA_OPTIONS:-'-Xmx4084m -Xms256m'} &&

does this really need 4 G to run?
that's ok for our cluster but might be a problem for others.

________________________________

In tools/picard/picard_CollectSequencingArtifactsMetrics.xml<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bwlang_tools-2Diuc_pull_2-23discussion-5Fr277131635&d=DwMCaQ&c=eRAMFD45gAfqt84VtBcfhQ&r=RDgR3MCuEAT5jbgfDKOU_QqPgpM8gSLjQ5SiCbZVpHQ&m=KplESfIgmb5b03YeCe7a3OHi_kd5qIdSMobMQFZ1HFE&s=YNxIZlQdwJ40SjXb7wjzkflF3zkDOfP-X9qCRPsX3O0&e=>:

> +        <option value="history">History</option>

+      </param>

+      <when value="cached">

+        <param name="ref_file" type="select" label="Use dictionary from the list" help="Select genome from the list">

+          <options from_data_table="picard_indexes">

+            <filter type="sort_by" column="2" />

+            <validator type="no_options" message="No indexes are available" />

+          </options>

+          <validator type="no_options" message="A built-in dictionary is not available for the build associated with the selected input file"/>

+        </param>

+      </when>

+      <when value="history">

+        <param name="ref_file" type="data" format="fasta" label="Use the following dataset to create dictionary" help="You can upload a FASTA sequence to the history from which Picard will automatically generate dictionary using CreateSequenceDictionary command" />

+      </when>

+    </conditional>

+    <!--<param name='reference_fasta_filename' type='data' label='Reference genome' help='last reference genome used is default'/>-->

delete?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bwlang_tools-2Diuc_pull_2-23pullrequestreview-2D228874616&d=DwMCaQ&c=eRAMFD45gAfqt84VtBcfhQ&r=RDgR3MCuEAT5jbgfDKOU_QqPgpM8gSLjQ5SiCbZVpHQ&m=KplESfIgmb5b03YeCe7a3OHi_kd5qIdSMobMQFZ1HFE&s=72KsbO8MjdjFw4Log8pdmHPEZaOdfsr8fNrhmPIqswo&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGFBZSC43NQ54LLO674337DPR6VQJANCNFSM4HEJGNQQ&d=DwMCaQ&c=eRAMFD45gAfqt84VtBcfhQ&r=RDgR3MCuEAT5jbgfDKOU_QqPgpM8gSLjQ5SiCbZVpHQ&m=KplESfIgmb5b03YeCe7a3OHi_kd5qIdSMobMQFZ1HFE&s=4l_6CHvZGXjKcSxIeynTJ6lvv_ObcuEreH1qDn31uCE&e=>.

2019-04-24 12:47 UTC, aerijman commented on tools/picard/picard_macros.xml
> +    _JAVA_OPTIONS=\${_JAVA_OPTIONS:-'-Xmx4084m -Xms256m'} &&
It works with 2G. In new commit is going to be 2G.

2019-04-24 12:51 UTC, aerijman commented on tools/picard/picard_CollectSequencingArtifactsMetrics.xml
> +    <!--<param name='reference_fasta_filename' type='data' label='Reference genome' help='last reference genome used is default'/>-->
Should I uncomment SPNs? 
I didn't test the SNPs yet. should I?

2019-04-24 13:24 UTC, bwlang commented on tools/picard/picard_CollectSequencingArtifactsMetrics.xml
> +    <!--<param name='reference_fasta_filename' type='data' label='Reference genome' help='last reference genome used is default'/>-->
Isn't that commented line repalced by the preceeding lines?
maybe I'm missing something.

2019-04-24 13:29 UTC, aerijman commented on tools/picard/picard_CollectSequencingArtifactsMetrics.xml
> +    <!--<param name='reference_fasta_filename' type='data' label='Reference genome' help='last reference genome used is default'/>-->
Yes. To be sure I tested it after deleting the line and it works.
I also have commented the line responsible to allow to input a vcf file and I was wondering if I should leave it commented, exclude it or uncomment it.

2019-04-24 13:31 UTC, bwlang commented on tools/picard/picard_CollectSequencingArtifactsMetrics.xml
> +    <!--<param name='reference_fasta_filename' type='data' label='Reference genome' help='last reference genome used is default'/>-->
I think we should dump the vcf line for now I don't see much value in it, can always add it later if needed

2019-04-24 14:45 UTC, aerijman commented
Is it ready to go now?

I accept guidance in the pull request to galaxyproject...

2019-04-24 15:02 UTC, bwlang commented
Yeah.. go ahead and send it upstream!

Brad

On Apr 24, 2019, at 10:45 AM, Ariel Erijman <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it ready to go now?

I accept guidance in the pull request to galaxyproject...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/bwlang/tools-iuc/pull/2#issuecomment-486272940>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AAAPBRCTURFZPCQBT63NIFTPSBXATANCNFSM4HEJGNQQ>.

2019-04-24 15:22 UTC, aerijman commented
From: Brad Langhorst <notifications@github.com>
Reply-To: bwlang/tools-iuc <reply@reply.github.com>
Date: Wednesday, April 24, 2019 at 11:02 AM
To: bwlang/tools-iuc <tools-iuc@noreply.github.com>
Cc: "Erijman, Ariel" <aerijman@fredhutch.org>, Author <author@noreply.github.com>
Subject: Re: [bwlang/tools-iuc] Add picard tool? (#2)

Yeah.. go ahead and send it upstream!

Brad

On Apr 24, 2019, at 10:45 AM, Ariel Erijman <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it ready to go now?

I accept guidance in the pull request to galaxyproject...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/bwlang/tools-iuc/pull/2#issuecomment-486272940>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AAAPBRCTURFZPCQBT63NIFTPSBXATANCNFSM4HEJGNQQ>.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bwlang_tools-2Diuc_pull_2-23issuecomment-2D486280090&d=DwMFaQ&c=eRAMFD45gAfqt84VtBcfhQ&r=RDgR3MCuEAT5jbgfDKOU_QqPgpM8gSLjQ5SiCbZVpHQ&m=M9M7bY-l5k2UC5v_wPqOLYxRtMT8FldVd4ATOorIhts&s=FXTa6DdVgCCY5BhXNYHpIiECh_kDIm8jsmzPkEpakG4&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGFBZSDH6ZGAUG3CIMLCGCTPSBY7RANCNFSM4HEJGNQQ&d=DwMFaQ&c=eRAMFD45gAfqt84VtBcfhQ&r=RDgR3MCuEAT5jbgfDKOU_QqPgpM8gSLjQ5SiCbZVpHQ&m=M9M7bY-l5k2UC5v_wPqOLYxRtMT8FldVd4ATOorIhts&s=9C_6oqodzRyOUiUYk8gkXXqDopkGGMb3VhI2ivhnzJ8&e=>.

2019-05-17 10:09 UTC, merged